[406.586885452] 2018-12-14 15:09:18,998 - INFO - launcher: Starting sanity checks
[407.586812973] 2018-12-14 15:09:18,999 - INFO - launcher: Checking for Python 3.5+
[408.585309982] 2018-12-14 15:09:19,000 - INFO - launcher: Checking console encoding
[408.585309982] 2018-12-14 15:09:19,000 - INFO - launcher: Setting console encoding to UTF-8
[409.584045410] 2018-12-14 15:09:19,001 - INFO - launcher: Ensuring we're in the right environment
[411.586046219] 2018-12-14 15:09:19,003 - INFO - launcher: Adding local bins/ folder to path
[5887.941598892] 2018-12-14 15:09:24,479 - INFO - launcher: Required checks passed.
[5888.945102692] 2018-12-14 15:09:24,480 - INFO - launcher: Optional checks passed.
[5889.943599701] 2018-12-14 15:09:24,481 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[10.1602654457092285] 2018-12-14 15:09:28,751 - WARNING - musicbot.config | In config.py::MainThread(9352), line 115 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[10.1602654457092285] 2018-12-14 15:09:28,751 - INFO - musicbot.config | In config.py::MainThread(9352), line 126 in run_checks: Using i18n: config/i18n/en.json
[10.1612644195556641] 2018-12-14 15:09:28,752 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 219 in _setup_logging: Set logging level to INFO
[10.1879363059997559] 2018-12-14 15:09:28,779 - DEBUG - musicbot.json | In json.py::MainThread(9352), line 8 in __init__: Init JSON obj with config/i18n/en.json
[10.2489907741546631] 2018-12-14 15:09:28,840 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 84 in __init__: Starting MusicBot 1.9.8_2
[10.2509899139404297] 2018-12-14 15:09:28,842 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 90 in __init__: Loaded autoplaylist with 2530 entries
[13.9287688732147217] 2018-12-14 15:09:32,520 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 912 in on_ready: Connection established, ready to go.
[13.9287688732147217] 2018-12-14 15:09:32,520 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 333 in _cache_app_info: Caching app info
[14.1899669170379639] 2018-12-14 15:09:32,781 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 734 in _scheck_ensure_env: Ensuring data folders exist
[14.1919703483581543] 2018-12-14 15:09:32,783 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 750 in _scheck_server_permissions: Checking server permissions
[14.1919703483581543] 2018-12-14 15:09:32,783 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 754 in _scheck_autoplaylist: Auditing autoplaylist
[14.1919703483581543] 2018-12-14 15:09:32,783 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 758 in _scheck_configs: Validating config
[14.1919703483581543] 2018-12-14 15:09:32,783 - DEBUG - musicbot.config | In config.py::MainThread(9352), line 216 in async_validate: Validating options...
[14.1919703483581543] 2018-12-14 15:09:32,783 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 761 in _scheck_configs: Validating permissions config
[14.1929724216461182] 2018-12-14 15:09:32,784 - DEBUG - musicbot.permissions | In permissions.py::MainThread(9352), line 92 in async_validate: Validating permissions...
[14.1929724216461182] 2018-12-14 15:09:32,784 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 929 in on_ready: Connected: 522843302501023757/Auto Music#9665
[14.1934945583343506] 2018-12-14 15:09:32,784 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 937 in on_ready: Owner:     440637080335417345/Kurai ≈çkami#1285

[14.1944985389709473] 2018-12-14 15:09:32,785 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 940 in on_ready: Guild List:
[14.1954970359802246] 2018-12-14 15:09:32,786 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 944 in on_ready:  - R3KT
[14.1954970359802246] 2018-12-14 15:09:32,786 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 1000 in on_ready: Not bound to any text channels
[14.1964967250823975] 2018-12-14 15:09:32,787 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 1026 in on_ready: Not autojoining any voice channels
[19.5290920734405518] 2018-12-14 15:09:38,120 - ERROR - musicbot.bot | In bot.py::MainThread(9352), line 900 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Ayoub Chebbi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Ayoub Chebbi\Desktop\New folder\MusicBot\musicbot\bot.py", line 2820, in on_voice_state_update
    player = await self.get_player(channel)
  File "C:\Users\Ayoub Chebbi\Desktop\New folder\MusicBot\musicbot\bot.py", line 424, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use ¬ßsummon to summon it to your voice channel.
[28.3803551197052002] 2018-12-14 15:09:46,971 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 2622 in on_message: 440637080335417345/Kurai ≈çkami#1285: ¬ßsummon
[29.7498095035552979] 2018-12-14 15:09:48,341 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 694 in deserialize_queue: Deserializing queue for 486953648601956403
[30.1195709705352783] 2018-12-14 15:09:48,710 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 416 in get_player: Created player via deserialization for guild 486953648601956403 with 1 entries
[30.1195709705352783] 2018-12-14 15:09:48,710 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 508 in on_player_finished_playing: Running on_player_finished_playing
[30.1195709705352783] 2018-12-14 15:09:48,710 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 670 in serialize_queue: Serializing queue for 486953648601956403
[30.1215701103210449] 2018-12-14 15:09:48,712 - INFO - musicbot.bot | In bot.py::MainThread(9352), line 1883 in cmd_summon: Joining R3KT/üé∂ Auto-Music üé∂
[30.1255664825439453] 2018-12-14 15:09:48,716 - DEBUG - musicbot.entry | In entry.py::MainThread(9352), line 56 in get_ready_future: Created future for audio_cache\youtube-T8fcbqDUwbU-Tropical_House_-_Hyper_Potions_-_Unbreakable_feat._Danyka_Nadeau_Monstercat_Release.webm
[30.1265676021575928] 2018-12-14 15:09:48,717 - FFMPEG - musicbot.player | In player.py::MainThread(9352), line 276 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-T8fcbqDUwbU-Tropical_House_-_Hyper_Potions_-_Unbreakable_feat._Danyka_Nadeau_Monstercat_Release.webm
[30.1295647621154785] 2018-12-14 15:09:48,720 - DEBUG - musicbot.player | In player.py::MainThread(9352), line 287 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x04568EB0> using <discord.voice_client.VoiceClient object at 0x04F02590>
[30.1315612792968750] 2018-12-14 15:09:48,722 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 451 in on_player_play: Running on_player_play
[30.1335611343383789] 2018-12-14 15:09:48,724 - DEBUG - musicbot.bot | In bot.py::MainThread(9352), line 670 in serialize_queue: Serializing queue for 486953648601956403
